---
#
# GitHub action to build the GCPy production environment with micromamba
# See: https://github.com/marketplace/actions/setup-micromamba
#
name: build-gcpy-environment

on:
  push:
    branches: [ "main", "dev", "dependabot/*" ]
  pull_request:
    # The branches below must be a subset of the branches above
    branches: [ "main", "dev" ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.8", "3.9", "3.10", "3.11", "3.12", "3.13"]
    steps:
      - name: Checkout the GCPy repository
        uses: actions/checkout@v3
      - name: Create "gcpy_env" environment
        uses: mamba-org/setup-micromamba@v1
        with:
          micromamba-version: 'latest'
          environment-file: docs/environment_files/environment.yml
          init-shell: bash
          cache-environment: true
          generate-run-shell: true
          post-cleanup: 'all'
      - name: Test if "import gcpy" works
        run: python -c "import gcpy"
        shell: micromamba-shell {0}
      - name: Test if we can create a plot
        run: python -m gcpy.examples.plotting.create_test_plot
        shell: micromamba-shell {0}

# Use Node.js version 20 to avoid deprecation warnings
runs:
  using: 'node20'
  main: 'main.js'
