---
#
# GitHub action to build the GCPy environment with micromamba
# See: https://github.com/marketplace/actions/setup-micromamba
#
name: build-gcpy-environment

on:
  push:
    branches: [ "main", "dev" ]
  pull_request:
    # The branches below must be a subset of the branches above
    branches: [ "main", "dev" ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.9"]
    steps:
      - name: Checkout the GCPy repository
        uses: actions/checkout@v2
      - name: Create the GCPy environment
        uses: mamba-org/setup-micromamba@v1
        with:
          micromamba-version: 'latest'
          environment-file: environment.yml
          environment-name: gcpy-test-env
          init-shell: bash
          cache-environment: true
          generate-run-shell: true
          post-cleanup: 'all'
      - name: Test if "import gcpy" works
        run: python -c "import gcpy"
        shell: micromamba-shell {0}
      - name: Test if we can create a plot
        run: python -m gcpy.examples.plotting.create_test_plot
        shell: micromamba-shell {0}
